
import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { db } from "../src/lib/db";
import { quests, seasons, dailyLogs, loot, users, questlines } from "../src/db/schema";
import { eq, sql, and } from "drizzle-orm";
import { v4 as uuidv4 } from "uuid";

async function verifyDbUpdate() {
    console.log("Starting DB Update Verification...");

    if (!process.env.DATABASE_URL) {
        console.error("DATABASE_URL not found!");
        process.exit(1);
    }

    try {
        // 1. Setup Data - Find existing or create dummy
        console.log("1. Finding or Creating User...");
        let userId = "";
        const existingUsers = await db.select().from(users).limit(1);
        if (existingUsers.length > 0) {
            userId = existingUsers[0].id;
        } else {
            userId = uuidv4();
            await db.insert(users).values({
                id: userId,
                email: "debug-test@test.com",
                displayName: "Debug Tester"
            });
        }
        console.log(`User ID: ${userId}`);

        console.log("2. Finding or Creating Season...");
        let seasonId = "";
        const existingSeasons = await db.select().from(seasons).where(eq(seasons.userId, userId)).limit(1);

        let season;

        if (existingSeasons.length > 0) {
            season = existingSeasons[0];
            seasonId = season.id;
        } else {
            seasonId = uuidv4();
            await db.insert(seasons).values({
                id: seasonId,
                userId: userId,
                title: "Debug Season",
                startDate: new Date(),
                endDate: new Date(),
                bossType: "Bug",
                bossHpMax: 100,
                bossHpCurrent: 100,
                status: "active"
            });
            const sList = await db.select().from(seasons).where(eq(seasons.id, seasonId));
            season = sList[0];
        }
        console.log(`Season ID: ${seasonId}`);

        console.log("3. Creating Test Quest...");
        const questId = uuidv4();
        await db.insert(quests).values({
            id: questId,
            seasonId: seasonId,
            title: "Debug Quest",
            type: "main",
            effort: "M",
            status: "todo"
        });
        console.log(`Quest ID: ${questId}`);

        // --- SIMULATE ACTION ---
        console.log("--- STARTING SIMULATED ACTION ---");

        const xpAmount = 10;
        const damage = 15;
        const now = new Date();

        console.log("A. Updating Quest Status...");
        await db.update(quests)
            .set({
                status: "done",
                completedAt: now,
            })
            .where(eq(quests.id, questId));

        console.log("B. Updating Season Stats with SQL math...");
        // Replicating: 
        // bossHpCurrent: sql`MAX(0, ${seasons.bossHpCurrent} - ${damage})`

        const xpCurrent = (season.xpCurrent || 0) + xpAmount;
        const xpLevel = Math.floor(xpCurrent / 100) + 1;

        await db.update(seasons)
            .set({
                xpCurrent: xpCurrent,
                xpLevel: xpLevel,
                bossHpCurrent: sql`GREATEST(0, ${seasons.bossHpCurrent} - ${damage})`,
            })
            .where(eq(seasons.id, seasonId));

        console.log("C. Generating Loot...");
        await db.insert(loot).values({
            id: uuidv4(),
            userId: userId,
            seasonId: seasonId,
            name: "Debug Loot",
            description: "Generated by debug script",
            rarity: "common",
        });

        console.log("D. Creating/Updating Daily Log...");
        const today = new Date().toISOString().split('T')[0];
        // Logic from actions.ts
        await db.insert(dailyLogs).values({
            id: uuidv4(),
            userId: userId,
            date: today,
            mainQuestsCompletedCount: 1,
            sideQuestsCompletedCount: 0,
        });

        console.log("--- ACTION SIMULATION COMPLETED SUCCESSFULLY ---");

        // Cleanup
        console.log("Cleaning up test quest...");
        await db.delete(quests).where(eq(quests.id, questId));
        // We leave the user/season/dailyLog to avoid breaking internal integrity too much, just a debug script.

    } catch (e) {
        console.error("!!! FATAL ERROR DURING SIMULATION !!!");
        console.error(e);
        process.exit(1);
    }
}

verifyDbUpdate();
